### ISSUE TITLE
Missing tab in series-list

### ISSUE THREAD

**Issue by KiandroDW** [BWindey/DodonaCLI#18]
When using ```dodona display``` it should have it so the id's are preceded with a tab, but in course it isn't and looks like this:
![image](https://github.com/BWindey/DodonaCLI/assets/119117295/1e2d1f3d-c771-4e70-9a14-7c18cdc4ba74)

Steps how to reproduce:
1. Select a course
2. use the command  ``` dodona display ```

**Comment by BWindey** [comment]
Fixed in [commit](https://github.com/BWindey/DodonaCLI/commit/211557f3a17c7ffd35b079b5c5605a9652a96bdc)

**Comment by BWindey** [comment]
Will be included in next merge

**Comment by BWindey** [comment]
Closed in the most recent version.
