### ISSUE TITLE
dodona sub shows incorect submission number

### ISSUE THREAD

**Issue by KiandroDW** [BWindey/DodonaCLI#22]
## Problem:
If you have more than 30 submissions on Dodona, there are multiple pages, but DodonaCLI ignores the actual number.
These are from the same exercise:
![Screenshot from 2023-12-05 17-26-03](https://github.com/BWindey/DodonaCLI/assets/119117295/78808ad4-499a-47cf-804b-740a00bbbe73)
![Screenshot from 2023-12-05 17-27-19](https://github.com/BWindey/DodonaCLI/assets/119117295/cbe7ba7e-3c49-42b7-9901-a041bbb0d7ba)

## How to recreate:
1. Have more than 30 submissions on a single Dodona exercise
2. Select that exercise in DodonaCLI
3. Use the command ``` dodona sub ```

**Comment by BWindey** [comment]
This is not supported by the Dodona API, so won't "fix" this either.
